name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout project
          uses: actions/checkout@v4  

        - name: Welcome message
          run: |
            echo "List and Read file"
            ls -ltra
            cat README.md 
