name: Generate ASCII Artwork

on:  
  push

jobs:
  ascii-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/Checkout@v4

    - name: List Repo files
      run: ls -ltra  

    - name: Executing shell script
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: dragon-text-file
        path: dragon.txt    

  deploy-job:
    needs: [ascii-job]
    runs-on: ubuntu-latest
    steps:
    - name: Download Dragon text file
      uses: actions/download-artifact@v3
      with:
        name: dragon-text-file

    - name: Read File
      run: cat dragon.txt

    - name: Deploy
      run: echo Deploying ... .. .
